import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-pharmacy-dir-fee-rebate-recovery",
  "engine": "recovery",
  "title": "Pharmacy DIR Fee & Rebate Recovery",
  "shortTitle": "Pharmacy DIR Fee and Rebate Recovery",
  "tagline": "Recalculate retroactive pharmacy adjustments and recover fees or rebates not supported by contract and performance data.",
  "industry": "Pharmacy Financial Operations",
  "buyer": "Retail and specialty pharmacy groups",
  "uiPort": 4646,
  "apiPort": 5646,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Pharmacy DIR Fee & Rebate Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes in one accountable workflow. Recalculate retroactive pharmacy adjustments and recover fees or rebates not supported by contract and performance data.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Pharmacy DIR Fee & Rebate Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("pbm-contract-library","PDF01","PBM contract library","Execute pbm contract library using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed pbm contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","PBM contract library Reference","text","PDF01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("network-amendment-control","PDF02","Network amendment control","Execute network amendment control using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed network amendment control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","Network amendment control Reference","text","PDF02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("prescription-claim-ingestion","PDF03","Prescription claim ingestion","Execute prescription claim ingestion using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed prescription claim ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","Prescription claim ingestion Reference","text","PDF03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("performance-measure-calculation","PDF04","Performance measure calculation","Execute performance measure calculation using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed performance measure calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","Performance measure calculation Reference","text","PDF04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("dir-estimate-accrual","PDF05","DIR estimate accrual","Execute dir estimate accrual using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed dir estimate accrual decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","DIR estimate accrual Reference","text","PDF05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("dir-fee-recalculation","PDF06","DIR fee recalculation","Execute dir fee recalculation using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed dir fee recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","DIR fee recalculation Reference","text","PDF06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("ger-guarantee-analysis","PDF07","GER guarantee analysis","Execute ger guarantee analysis using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed ger guarantee analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","GER guarantee analysis Reference","text","PDF07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("brand-generic-mix-validation","PDF08","Brand generic mix validation","Execute brand generic mix validation using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed brand generic mix validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","Brand generic mix validation Reference","text","PDF08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("network-rebate-calculation","PDF09","Network rebate calculation","Execute network rebate calculation using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed network rebate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","Network rebate calculation Reference","text","PDF09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("remittance-adjustment-matching","PDF10","Remittance adjustment matching","Execute remittance adjustment matching using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed remittance adjustment matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","Remittance adjustment matching Reference","text","PDF10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("negative-balance-review","PDF11","Negative balance review","Execute negative balance review using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed negative balance review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","Negative balance review Reference","text","PDF11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("pharmacy-dispute-package","PDF12","Pharmacy dispute package","Execute pharmacy dispute package using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed pharmacy dispute package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","Pharmacy dispute package Reference","text","PDF12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("pbm-response-workflow","PDF13","PBM response workflow","Execute pbm response workflow using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed pbm response workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","PBM response workflow Reference","text","PDF13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("cash-credit-reconciliation","PDF14","Cash credit reconciliation","Execute cash credit reconciliation using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed cash credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","Cash credit reconciliation Reference","text","PDF14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]}),
feature("pbm-store-analytics","PDF15","PBM store analytics","Execute pbm store analytics using PBM agreements, network amendments, prescriptions, adjudication responses, performance scores, DIR fees, GER guarantees, rebates, remittances, and disputes.","Produce a governed pbm store analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pharmacy / Prescription Population","text","Pharmacy / Prescription Population · Standard Case"],["caseReference","PBM store analytics Reference","text","PDF15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",548750],["supportedAmount","Evidence-Supported Amount","currency",460950],["domainDriver","Adjustment Type","select","DIR fee",["DIR fee","GER true-up","Network rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["PBM contract library case","Network amendment control case","Prescription claim ingestion case","Performance measure calculation case","DIR estimate accrual case"]})
]);
